#!/usr/bin/env bash
# 0-transfer_file: script to transfer a file using SCP

# check if less than 3 parameters passed
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# scp transfers the file from client to user ~/
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
