#!/usr/bin/env bash
# This script installs and configures nginx
# Set to listen on port 80 
# when queried at its root / with a GET request using curl,
# it returns a page with the string Hello World!

# Update package lists and install Nginx
apt-get -y update
apt-get -y install nginx

# Ensure nginx is running
service nginx start

# Write content to index.html
cat > /var/www/html/index.html << EOF
Hello World!
EOF

# Restart Nginx to apply changes
nginx -s reload
