#!/usr/bin/env bash
# Bash script that pings an IP address passed as argument 5 times
# If no argument is passed, it displays error:
# Usage: script_name {IP_ADDRESS}
set -o pipefail

if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
