#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop

i=0
while [ $i -lt 10 ]	# Loop continues while i is less than 10
do
	echo "Best School"
	i=$((i+1))	# increment i by 1 after each iteration
done
