#!/usr/bin/env bash
# Bash script that edits the /etc/hosts file and 
# resolves localhost to 127.0.0.2 and adds facebook.com to 8.8.8.8 

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
