#!/usr/bin/env bash
# This gets Apache to run on the container and to return a page containing
# "Hello Holberton" when querying the root of it.
apt-get -y update
apt-get -y install apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
